# Generated by Django 5.2.5 on 2025-09-02 01:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('resolved', models.TextField(blank=True, null=True, verbose_name='Descrição da resolução')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('predicted_date', models.DateField(verbose_name='Data prevista')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('days_delay', models.PositiveIntegerField(default=0, help_text='Número de dias de atraso (calculado automaticamente).', verbose_name='Dias de atraso')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada'), ('unresolved', 'Não Resolvida')], default='open', max_length=12, verbose_name='Status')),
                ('rate', models.PositiveSmallIntegerField(blank=True, help_text='Avaliação de 1 a 5 dada à ordem de serviço.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuário solicitante')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='serviceorde_status_21921c_idx'), models.Index(fields=['priority'], name='serviceorde_priorit_2950a5_idx'), models.Index(fields=['predicted_date'], name='serviceorde_predict_3005f1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__isnull', True), models.Q(('rate__gte', 1), ('rate__lte', 5)), _connector='OR'), name='workorder_rate_1_5_or_null'), models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('predicted_date'))), name='workorder_start_lte_predicted'), models.CheckConstraint(condition=models.Q(('completion_date__isnull', True), ('completion_date__gte', models.F('start_date')), _connector='OR'), name='workorder_completion_gte_start_or_null')],
            },
        ),
    ]
